### ISSUE TITLE
Error requiring shards

### ISSUE THREAD

**Issue by teodor-pripoae** [AtomLinter/linter-crystal#19]
Hi,

I'm having the following error when I require a shard and hit save.

```
require "pool/connection"
```

Error:

```
while requiring "pool/connection": can't find file 'pool/connection' relative to '..../my-project/src' at line 2 col 1.
```

The shard is present in shard.yml and I can compile the program with command line.

**Comment by keplersj** [comment]
I've ran into this issue before. I've been thinking about how to solve this
and I'm unsure of a proper solution.

**Comment by teodor-pripoae** [comment]
I think it may exist a compile flag to specify extra import paths.

Then, you can search in all parent directories of current file for directories named `.shards` and add them to the build command with that extra flag.

I'll ask this question on crystal issue tracker.

**Comment by teodor-pripoae** [comment]
Hi @keplersj 

I think the `CRYSTAL_PATH` can be set with the first subdirectory of current file. What do you think ?

**Comment by teodor-pripoae** [comment]
Solved the issue for myself using the following code:

``` coffeescript
projectPath = activeEditor.project.getPaths()[0]
path = '/usr/local/Cellar/crystal-lang/0.15.0/src:' + projectPath + '/libs'
const opts = {env: {'CRYSTAL_PATH': path}}
resolve(helpers.exec(command, args, opts).then(output => {
...
```

There are two problems:
- currently the crystal stdlib path is hardcoded (I can get it by parsing `crystal env`, but I don't know how to do it in atom plugins at startup)
- I'm assuming the project root directory is the first open project in atom. It will not work with multiple projects or with only one file opened without any project. I think it can be done by going one directory up at a time and check for any shards.yml, but I currently don't have the time to do it.

**Comment by keplersj** [comment]
I've begun to resolve this, I'll finish my patch sometime later this week.
